---
title: "LSE DS105M - Fundamentals of Data Science"
subtitle: "(2022/23 summer revision)"
---

# 📑 Course Content

This course will cover the fundamentals of data, with an aim to understanding how data is generated, how it is collected, how it must be transformed for use and storage, how it is stored, and the ways it can be retrieved and communicated. The course will also cover workflow management for typical data transformation and cleaning projects, frequently the starting point and most time consuming part of any data science project. This course uses a project-based learning approach towards the study of online publishing and group-based collaboration, essential ingredients of modern data science projects.

It introduces the principles and applications of the electronic storage, structuring, manipulation, transformation, extraction, and dissemination of data. This includes data types, how data is stored and recorded electronically, the concept and fundamentals of databases. It also covers how data is formatted and communicated. It presents basic methods for obtaining data from the Internet, including simple methods for web scraping and the use of APIs to submit queries that return structured data. Finally, it covers methods for formatting and publishing data.

Sharing and publishing data will also form a key part of this module and will include key skills in on-line publishing, including the elements of web design, the technical elements of web technologies and web programming, as well as the use of revision-control and group collaboration tools such as GitHub. Each student will build an interactive website based on content relevant to their domain-related interests, and will use GitHub for accessing and submitting course materials and assignments. The final project will involve group work to create a data-based website published on GitHub.

This module is not designed to be a hands-on introduction to the use of databases, but does introduce the concepts of databases. For more detailed learning on databases, we will encourage students to take ST207 Databases.

# ℹ️ Course Information

## Teacher Responsible

Dr. [Jonathan Cardoso-Silva](https://www.lse.ac.uk/DSI/People/Jonathan-Cardoso-Silva) & Dr. [Julio Amador Diaz Lopez](https://www.lse.ac.uk/DSI/People/Julio-Amador-Diaz-Lopez).

## Availability
This module is designed for students on social science degree programmes who do not have A-level Mathematics (e.g. in Anthropology, Law, and Social Policy).

## Course Administration
If you have any administrative queries about this course please contact us at [dsi.admin@lse.ac.uk](http://dsi.admin@lse.ac.uk/).

## Lectures

<mark class="todo"></mark>

## Classes

-   Classes run from Week 01 until Week 11, with the exception of reading week (Week 06).

## Formative coursework

<mark></mark>In the initial sessions, students will work on weekly, structured problem sets in the staff-led class sessions. Examples of exercises involve: setting up account, repositories and pages on GitHub, accessing terminal and computer servers.

Later on, students will be expected to work on their group projects in the staff-led class sessions.

## Assessment

<mark class="todo"></mark>

## Feedback
We want to hear from you!

The DSI is always seeking to improve the student experience within courses. If you have comments, queries or issues, please let us know. You can send administrative related thoughts to [dsi.admin@lse.ac.uk](http://dsi.admin@lse.ac.uk/) and thoughts on teaching can be raised with your seminar leader.

It is important that student concerns are addressed and students have a say in the running of their course, so you also have your course forum that can be used as a place to discuss the course with your fellow students and your home Department will hold [SSLCs](https://info.lse.ac.uk/current-students/Assets/Articles/student-voice) at least once per term. 

Please pass on your thoughts about the course to your programme's Academic Representative so that they can raise these at SSLC meetings. Your Department will then be able to forward these to the DSI, enabling us to improve the course in future.
