---
title: "📒 Week 01 - Preparing for next week's lab"
date: 1 September 2022
date-meta: 1 September 2022
---

## 💻 Labs

We do not have classes this week. Instead, we recommend you use this time to learn or revisit the basics of a programming language (either R or Python).

See sections below for advice on how to do that.

## 📒 Preparing for the next week

- Join the Slack group of this course [(more info)](/communication.qmd)
- Use this time to learn or revisit basic programming skills. Remember: [later in this course](/syllabus.qmd), you will start working on a group project that will require some element of coding. You are free to use either R or Python. 

## 🔖 Recommended Resources

- [Digital Skills Lab](https://info.lse.ac.uk/current-students/digital-skills-lab) offer workshops on R and Python skills.
- Checkout this summer's [LSE Careers Skill Accelerator programme](https://twitter.com/LSECareers/status/1534868470495596545). Some of the self-paced courses will remain available until the end of the year.

