---
title: "👨‍🏫 Week 09 - Managing your data science workflow"
date: 22 November 2022
date-meta: 22 November 2022
from: markdown+emoji
author: Dr. Jon Cardoso-Silva
---


::: {.callout-tip collapse="true"}
## What about Natural Language Processing (NLP)?

I had planned a small introduction to [spaCy](https://spacy.io/usage/spacy-101#annotations-token), a package in Python that handles text as data, but we will not have the time to talk about NLP today!

**Unstructured data (text, audio & image)** was always planned to be taught next week anyways. So join on Week 10 for an intro to text pre-processing, when I will then focus on tokenization — the process of breaking sentences into words and counting/describing them (without any `for` loops!)

We will continue to explore the topic of text data on Week 11 when Prof. [Ken Benoit](https://kenbenoit.net/) will come and deliver a talk about text mining applications. 

:::


# 🖥️ Part I - Conda environments (45-50 min)

In the first part of the lecture, we will explore [`conda` environments](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) together (bring your 💻laptops, and perhaps also coffee!). 

And in the labs, you will practice how to share these environments via Github and also how to use Github more effectively as a team. You will learn about the process of [Pull Requests](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) for teams.

::: {.callout-note collapse="false"}
💡You will be assessed on knowledge of these best practices as part of your final project. Check the [Project Marking Criteria](/main/assessments.html#projects-marking-criteria): Source Code | Organisation and  Source Code | Collaboration.

:::

<details><summary>**Open to see lecture notes**</summary>

## Lecture Notes

This is an interactive lecture. I will teach you about [`conda` environments](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) and we will compare how everyone's conda and python settings are different.

### 🤔 What is in my `conda`?

#### Step 1. 

**Which version of python do you have?** Open your terminal and type:

```python
python --version
```

Compare your version to those of your colleagues.

#### Step 2. 

**Which version of `conda` do you have?** Open your terminal and type:

```python
conda list
```

You should see a list of all packages you have installed, or came installed by default, in your `conda` default environment. 

What version of `jupyterlab` do you have installed? What about `pandas`? Compare the version of your packages to those of your colleagues. Are there any differences?

#### Step 3. 

**Let's generate some data!** Run the command below in the terminal to save the content of `conda list` to a text file. Replace my username for yours:

```python
conda list >> conda_list_jonjoncardoso.txt
```

#### Step 4. 

**I will ask you to upload the file you created to Slack**

#### Step 5. 

I will then combine all of our data and we will explore the discrepancies in the versions of packages we are all likely to use.

### ⚙️ How do we "fix" everyone's environment?

#### Step 6. 

In the terminal, `cd` to the directory where you keep all the files of your project.

#### Step 7.

**Create a conda environment**

💡 Useful link: [Managing `conda` environments`](https://conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html)

```python
conda create --prefix .\venv python=3.10
```

#### Step 8.

**Activate the environment:**

::: {.panel-tabset}
## macOS/Unix Users
```python
source activate .\venv
```

## Windows
```python
activate .\venv
```
:::

#### Step 9.

**What's different about this conda environment?**

```python
conda list
```

#### Step 10.

**Create a new file called `requirements.txt`** and paste the following there:

```python
matplotlib==3.5.3 # version required for plotnine
plotnine==0.10.1 # Python version of ggplot2

numpy>=1.22
pandas==1.4.2
scikit-learn==1.1.3

### UTILS
jupyterlab==3.4.2
tqdm==4.62.0
```

#### Step 11.

**Try to install it with `conda`**:

```python
conda install --file requirements.txt
```

Why can't we install all packages?

### Step 12.

Install it with `pip`:

::: {.panel-tabset}
## macOS/Unix Users
```python
conda install pip
which pip
```

## Windows
```python
conda install pip
where.exe pip
```
:::

Then:

```python
pip install -r requirements.txt
```

#### Step 12.

**How does the conda environment look like now?**

```python
conda list
```

</details>


## ☕ Coffee Break (10 min)

Use this time to chat, stretch, drink some coffee or just relax for a bit by yourself.

## 🖥️ Part II - Databases (45-50 min)

**Databases**: what is it? what is SQL? And how to connect to a database directly through pandas. Initially, this content will come on _🗓️ Week 08_ but we didn't have the time for that.

<details><summary>**Open to see lecture notes**</summary>

### Useful links

- **Relational Database Management System (RDBMS)**
    - [Oracle: What is a Relational Database?](https://www.oracle.com/uk/database/what-is-a-relational-database/)
    - [Google: What is a Relational Database?](https://cloud.google.com/learn/what-is-a-relational-database)
- **Famous [Open-source](/slides/week02_slides_part1.html#/history) RDBMS:**
    - [MySQL](https://www.mysqltutorial.org/)
    - [PostgreSQL](https://www.postgresql.org/docs/15/index.html)
- **SQL**:
    - Good step-by-step [SQL Tutorial](https://www.w3schools.com/sql/sql_intro.asp)

### Follow the steps

#### Step 13.

**Download and Install** [DBrowser for SQLite](https://sqlitebrowser.org/)

#### Step 14. 

**Download** this sample data called [ChinookDatabase](https://github.com/lerocha/chinook-database/blob/master/ChinookDatabase/DataSources/Chinook_Sqlite.sql)

#### Step 15.

Import Chinook Database to the database using DBrowser

</details>

