---
title: "💻 Week 04 - Lab Roadmap (90 min)"
date: 6 February 2023
date-meta: 6 February 2023
author: Anton Boichenko
---

This week it is time for you to go beyond your own machine and even beyond a cloud machine and visit the Internet! 

In today's lab, we will get familiar with web-scraping, a notion that describes the practices of automated data acquisition from the Internet. In this lab, we will cover the fundamental skills of web-scraping and learn how to save the results of it to a dataframe. These skills are not only essential for your data collection for this course but will be exceptionally useful for you in your own research.  

<details><summary>Part 1: Exploring CIVICA (50 min)</summary>
## Part 1: Exploring CIVICA
<p></p>

You might have heard of [CIVICA](https://www.civica.eu/who-we-are/about-civica/) before. It is a body that unites several European universities to collaborate in the areas of social sciences, humanities, business and public policy. CIVICA hosts [Data Science Seminar series](https://socialdatascience.network/index.html#schedule) that might be of interest to you. Today we will collect information on some of the seminars. Maybe you can use it in the future! 

**Our main task** is to create a dataframe that would contain:

1. names of the seminars 
2. names of speakers of those seminars
3. dates of the seminars
4. bios of the speakers from each individual event 

🤔 **Stop and think**. Before you start following the instructions. Can you think of a way to acquire this information using the CIVICA website?


🤝 **WORKING TOGETHER**

1. Go to the [Data Science Seminar series](https://socialdatascience.network/index.html#schedule) website.
2. Inspect the page and find the way to the name of the first event on the page. 
3. Send a GET request to the website and get the name of the first event on the page. 
4. Print this name. 

🎯 **ACTION POINTS**

1. Using the skill that you have just learned acquire the names of all the events.
2. Save them all to a list.
3. Do the same with the dates of the events and speaker names and save them to separate lists. 

The **solutions** for this task will be sent to you in the form of computational notebooks after the lab. 


</details>

<details><summary>Part 2: Let's make a dataframe (20 min)</summary>

## Part 2: Let's make a dataframe

Now, it's your turn to work independently and create a dataframe out of the information that we have collected. 

🎯 **ACTION POINTS** 

You should have three lists at this point: names of events, names of speakers, and dates of events. 

1. Search online how to convert these lists to a dataframe. 
2. Save the dataframe as a CSV file and call it `CIVICA_seminars.csv`. 


</details>

<details><summary> 🎁 Bonus task: Tell me more (20-25 min)</summary>

## Bonus task: Tell me more

If you are curious to explore more web-scraping (and also get some hints for your summative) let's take a look into a more complicated task.

🎯 **ACTION POINTS** 

Each individual event page has a bio (a description) of the speaker. Let's add those to our dataframe!

1. Go to an event's page and find out how to access the description of the speaker.
2. Iterate through all the scraped events and extract information on speakers.
3. Add this information to the final dataframe. 

**Important**: the last collected link returns an error. Feel free to delete it. 

</details>

