---
title: "DS105M - W07 - Part I - Helpdesk"
author: "Jon"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Setup

Import required libraries:

```{r, message=FALSE, warning=FALSE}
library("httr")
library("tidyverse")
library("jsonlite")
```

## Key

```{r}
# saving your API key
api_key <- "sROtzp89HIqkAAy1g5Vai9mGX6afqA1i"
```

```{r}
base_url = "https://api.nytimes.com/svc/search/v2/articlesearch.json"
```

```{r}
# sending a request
# GET(base_url_test, query = list( "q" = "stock", "begin_date" = 20181218, "end_date" = 20201230, "sort" = "newest", "api-key" = "------", "page" = 80))

# response <- GET(base_url, query = list("api-key" = api_key))

response <- GET(base_url, query = list( "q" = "stock", "begin_date" = 20181218, "end_date" = 20201230, "sort" = "newest", "api-key" = api_key, "page" = page))
```

```{r}

df = data.frame()

for(page in seq(0, 100)){
  
  response <- ...
  
  current_df <- ...
  
  df <- bind_rows(df, current_df)
  
}

```

```{r}
#api_key <- ...

response <- GET(base_url, query = list( "q" = "stock", "begin_date" = 20181218, "end_date" = 20201230, "sort" = "newest", "api-key" = api_key, "page" = 80))

# parse the response
resp_json <- content(response, as="text", encoding = "UTF-8")

resp_table <- as.data.frame(fromJSON(resp_json))


head(resp_table)
```

```{r}
resp_json
```

```{r}

```

```{r}

```

```{r}
docs <- resp_json$response$docs
```

```{r}
length(docs)
```

```{r}
library(jsonlite)
fromJSON(resp_json)
```
