---
title: "💻 Week 03 - Summative assessment"
date: 16 September 2022
date-meta: 16 September 2022
author: Anton Boichenko
---

Welcome to your first summative assessment for this course! We hope you have enjoyed interacting with the cloud and are ready to put your skills to use. This summative will consist of 4 parts and will cover several areas of your cloud-related skills. 

### Things to know before you start:  
1. You will need to upload some parts of this assignment on Moodle.
2. The **deadline** for this assignment is on Moodle as well.
3. You will be granted a maximum of 10 points for the whole assignment. You will see how much each task is right next to the tasks' names. 
4. You will need to take screenshots, [here is how you can do that](https://www.take-a-screenshot.org/). 
4. Read the instructions carefully and make sure you follow them.

## P1: Book worms (2 points)

🎯 **ACTION POINTS**

1. Open the bash shell on your local machine.
2. Create a .txt file called `my_fav_book.txt`.
3. Add the title and the author of your favourite book to the file in the following way:

    ```
    Title: Aristotle

    Author: Politics
    ```

3. Create a folder on your cloud machine called `summative_03` and copy that .txt file to that folder. The folder should be located in the following way: `/home/<username>/summative_03`.  
    **Make sure you copy the file** from your local machine to the cloud and not create an identical one straight on the cloud machine.  
4. Connect to the cloud machine.
5. Using the cloud bash shell, print the content and the metadata (feel free to look at our last week's materials) of this file. Then, take a screenshot of the result of those commands running. Please, make sure that your username is visible in the screenshot. 

## P2: Run the code in the cloud (3 points)

🎯 **ACTION POINTS**

1. Go to your cloud machine.
2. Create a Python or an R script called `script.py` or `script.R`, respectively, **in the folder** called `summative_03`. 
3. The script must do the following:
    1. Print your AWS username (the one you were provided at the beginning of the course)
    2. Print the current time (you can search for ways to do that)
    3. Wait for 10 seconds
    4. Print the current time again
4. Run the script and take a screenshot of the results of running it. 
5. Run the script again **but this time** make a tweak to your bash command that we discussed last week. The tweak should allow you to interact with your bash shell even while Python is running. To prove that it has worked, call an `ls` command while Python is waiting for 10 seconds in-between printing commands. 
    Take a screenshot of the result of this code running. 
6. Print the metadata of your file and take a screenshot of it. 

## P3: It's time to search (5 points)

🎯 **ACTION POINTS**

1. Go to your cloud machine.
2. Navigate to the `/home/admin/week_03` directory. You will see a lot of `.md` files there. One of them is yours.
3. Find the file that was created for you.  
    This part is a bit tricky. What you need to do is to go through these files one by one and find the one that has your LSE ID in it. 
4. Copy this file to the `summative_03` folder on **your** user within the cloud machine. 
5. Change the permissions on this file for you to be able to edit it.
6. Edit the file and answer the questions in it.
7. Print the content of the file and the file's metadata. Take a screenshot of both.  

## P4: Submit (no points)

Upload your screenshots to Moodle togther with the infromation required. 

