---
title: "📒 Week 02 - Preparing for the lab"
date: 1 September 2022
date-meta: 1 September 2022
---


In our labs this week, we will learn about the command line — also called the terminal. Follow the tips below to get the most out of our session:

- Bring your **laptops**. Tablets are not suitable for this class.
- Students who use **Windows** will have to install additional software on their laptops. We will dedicate some of our time in the lab to this, but if you want, you could try to follow Steps 1-4 of the Canonical tutorial [^*] before coming to class.
- In the lab we will practice the concepts introduced in this week's lecture. If a concept introduced in the lecture was not clear to you, revisit the slides and bring your questions to the lab.
- Browse the [🔖 Week 02 Appendix](/weeks/week02/appendix.qmd) page:
    - skim through the blog posts and articles therein to reinforce concepts covered in the lecture,
    - bookmark whatever you feel could be relevant to you in the future
- Try to replicate the lecture demo before coming to the lab. 

[^*]: Tutorial: ["Install Ubuntu on Wsl2 on Windows 11 with GUI Support"](https://ubuntu.com/tutorials/install-ubuntu-on-wsl2-on-windows-11-with-gui-support)